export const useShellBridge: any;
export const useShell: any;
export const eventBus: any;
declare const _: any;
export default _;
export const toast: any;
export const useToast: any;
export const getErrorMessage: any;
export const attachToastErrorHandler: any;
export const toastBus: any;
export const ToastViewport: any;
export const ToastProvider: any;
